### ISSUE TITLE
求助：安装不了

### ISSUE THREAD

**Issue by QiangF** [sheepduke/silver-brain#6]
1. 安装 sqlite 3, libcurl4-gnutls-dev 
2. 然后运行 bootstrap.sh
3. ros install sbcl-bin
4. ./install.sh
错误：
    ; file: /etc/roswell/dump-sbcl.lisp
    ; in: DEFUN DELETE-COMPILER-INFORMATION-SBCL
    ;     (SETF (SB-INT:INFO :FUNCTION :INLINEP ROSWELL.DUMP.SBCL::S) :NOTINLINE)
    ; --> LET* FUNCALL LET LET LOCALLY 
    ; ==>
    ;   (THE SB-C::INLINEP #:NEW)
    ; 
    ; caught WARNING:
    ;   Derived type of #:NEW is
    ;     (VALUES (MEMBER :NOTINLINE) &OPTIONAL),
    ;   conflicting with its asserted type
    ;     (MEMBER INLINE SB-EXT:MAYBE-INLINE NOTINLINE NIL).
    ;   See also:
    ;     The SBCL Manual, Node "Handling of Types"
    ; 
    ; caught WARNING:
    ;   Derived type of #:NEW is
    ;     (VALUES (MEMBER :NOTINLINE) &OPTIONAL),
    ;   conflicting with its asserted type
    ;     (MEMBER INLINE SB-EXT:MAYBE-INLINE NOTINLINE NIL).
    ;   See also:
    ;     The SBCL Manual, Node "Handling of Types"
    ; 
    ; compilation unit finished
    ;   caught 2 WARNING conditions
    Unhandled QUICKLISP-CLIENT:SYSTEM-NOT-FOUND in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                            {10005104C3}>:
    System "silver-brain" not found

    Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10005104C3}>
    0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<QUICKLISP-CLIENT:SYSTEM-NOT-FOUND {10041EA4F3}> #<unused argument> :QUIT T)
    1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<QUICKLISP-CLIENT:SYSTEM-NOT-FOUND {10041EA4F3}>)
    2: (INVOKE-DEBUGGER #<QUICKLISP-CLIENT:SYSTEM-NOT-FOUND {10041EA4F3}>)
    3: (CERROR "Try again" QUICKLISP-CLIENT:SYSTEM-NOT-FOUND :NAME "silver-brain")
    4: ((LABELS QUICKLISP-CLIENT::RECURSE :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) "silver-brain")
    5: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) {10041E108B}>)
    6: (QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY "silver-brain")
    7: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "silver-brain" :PROMPT NIL)
    8: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)) #<unused argument> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {10041E
    098B}>) [fast-method]
    9: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION :AROUND (QL-IMPL:SBCL T)) #<QL-IMPL:SBCL {1005026EE3}> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKL
    ISP-CLIENT:QUICKLOAD) {10041E098B}>) [fast-method]
    10: ((:METHOD QUICKLISP-CLIENT:QUICKLOAD (T)) (SILVER-BRAIN) :PROMPT NIL :SILENT T :VERBOSE NIL) [fast-method]
    11: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT:QUICKLOAD) {10041D948B}>)
    12: (SB-INT:SIMPLE-EVAL-IN-LEXENV (QUICKLISP-CLIENT:QUICKLOAD (QUOTE (SILVER-BRAIN)) :SILENT T) #<NULL-LEXENV>)
    13: (SB-INT:SIMPLE-EVAL-IN-LEXENV (PROGN (ROSWELL:ENSURE-ASDF) (QUICKLISP-CLIENT:QUICKLOAD (QUOTE (SILVER-BRAIN)) :SILENT T)) #<NULL-LEXENV>)
    14: (EVAL-TLF (PROGN (ROSWELL:ENSURE-ASDF) (QUICKLISP-CLIENT:QUICKLOAD (QUOTE (SILVER-BRAIN)) :SILENT T)) NIL NIL)
    15: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (PROGN (ROSWELL:ENSURE-ASDF) (QUICKLISP-CLIENT:QUICKLOAD (QUOTE (SILVER-BRAIN)) :SILENT T)) NIL)
    16: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /home/q/desktop/silver-brain/backend/roswell/silver-brain.ros" {100415
    C843}> #<SB-IMPL::STRING-INPUT-STREAM {100415E1E3}>) {100415E5F3}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
    17: ((FLET SB-FASL::THUNK :IN LOAD))
    18: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<CLOSURE (FLET SB-FASL::THUNK :IN LOAD) {7F72C3F8E98B}> #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /h
    ome/q/desktop/silver-brain/backend/roswell/silver-brain.ros" {100415C843}> #<SB-IMPL::STRING-INPUT-STREAM {100415E1E3}>) {100415E5F3}>)
    19: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /home/q/desktop/silver-brain/backend/roswell/silver-bra
    in.ros" {100415C843}> #<SB-IMPL::STRING-INPUT-STREAM {100415E1E3}>) {100415E5F3}> NIL)
    20: (LOAD #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /home/q/desktop/silver-brain/backend/roswell/silver-brain.ros" {100415C843}> #<SB-IMPL:
    :STRING-INPUT-STREAM {100415E1E3}>) {100415E5F3}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
    21: ((FLET ROSWELL::BODY :IN ROSWELL:SCRIPT) #<SB-SYS:FD-STREAM for "file /home/q/desktop/silver-brain/backend/roswell/silver-brain.ros" {100415C843}>)
    22: (ROSWELL:SCRIPT #P"./roswell/silver-brain.ros")
    23: (ROS.SCRIPT.DUMP::EXECUTABLE ROSWELL.DUMP.SBCL::SBCL ("./roswell/silver-brain.ros"))
    24: (ROS.SCRIPT.DUMP::MAIN "executable" "./roswell/silver-brain.ros")
    25: (SB-INT:SIMPLE-EVAL-IN-LEXENV (APPLY (QUOTE ROS.SCRIPT.DUMP::MAIN) ROSWELL:*ARGV*) #<NULL-LEXENV>)
    26: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:QUIT (APPLY (QUOTE ROS.SCRIPT.DUMP::MAIN) ROSWELL:*ARGV*)) #<NULL-LEXENV>)
    27: (EVAL-TLF (ROSWELL:QUIT (APPLY (QUOTE ROS.SCRIPT.DUMP::MAIN) ROSWELL:*ARGV*)) NIL NIL)
    28: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (ROSWELL:QUIT (APPLY (QUOTE ROS.SCRIPT.DUMP::MAIN) ROSWELL:*ARGV*)) NIL)
    29: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS NIL {10029A2F53}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
    30: ((FLET SB-FASL::THUNK :IN LOAD))
    31: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<CLOSURE (FLET SB-FASL::THUNK :IN LOAD) {7F72C3F8F4EB}> #<CONCATENATED-STREAM :STREAMS NIL {10029A2F53}>)
    32: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<CONCATENATED-STREAM :STREAMS NIL {10029A2F53}> NIL)
    33: (LOAD #<CONCATENATED-STREAM :STREAMS NIL {10029A2F53}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
    34: ((FLET ROSWELL::BODY :IN ROSWELL:SCRIPT) #<SB-SYS:FD-STREAM for "file /etc/roswell/dump.ros" {100299E733}>)
    35: (ROSWELL:SCRIPT "/etc/roswell/dump.ros" "executable" "./roswell/silver-brain.ros")
    36: (ROSWELL:RUN ((:EVAL "(ros:quicklisp)") (:SCRIPT "/etc/roswell/dump.ros" "executable" "./roswell/silver-brain.ros") (:QUIT NIL)))
    37: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:RUN (QUOTE ((:EVAL "(ros:quicklisp)") (:SCRIPT "/etc/roswell/dump.ros" "executable" "./roswell/silver-brain.ros") (
    :QUIT NIL)))) #<NULL-LEXENV>)
    38: (EVAL (ROSWELL:RUN (QUOTE ((:EVAL "(ros:quicklisp)") (:SCRIPT "/etc/roswell/dump.ros" "executable" "./roswell/silver-brain.ros") (:QUIT NIL)))))
    39: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(progn #-ros.init(cl:load \"/etc/roswell/init.lisp\"))") (:EVAL . "(ros:run '((:eval\"(ros:quicklisp)\")(:s
    cript \"/etc/roswell/dump.ros\"\"executable\"\"./roswell/silver-brain.ros\")(:quit ())))")))
    40: (SB-IMPL::TOPLEVEL-INIT)
    41: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
    42: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SAVE-LISP-AND-DIE))
    43: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

    unhandled condition in --disable-debugger mode, quitting
    Unhandled UIOP/RUN-PROGRAM:SUBPROCESS-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                            {10005304C3}>:
    Subprocess with command "/usr/bin/ros  -Q  -L sbcl-bin dump executable ./roswell/silver-brain.ros"
    exited with error code 1

    Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10005304C3}>
    0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {10036E4EC3}> #<unused argument> :QUIT T)
    1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {10036E4EC3}>)
    2: (INVOKE-DEBUGGER #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {10036E4EC3}>)
    3: (CERROR "IGNORE-ERROR-STATUS" UIOP/RUN-PROGRAM:SUBPROCESS-ERROR :COMMAND "/usr/bin/ros  -Q  -L sbcl-bin dump executable ./roswell/silver-brain.ros" :CODE 1
    :PROCESS NIL)
    4: (UIOP/RUN-PROGRAM::%CHECK-RESULT 1 :COMMAND "/usr/bin/ros  -Q  -L sbcl-bin dump executable ./roswell/silver-brain.ros" :PROCESS NIL :IGNORE-ERROR-STATUS NI
    L)
    5: (UIOP/RUN-PROGRAM::%USE-SYSTEM "/usr/bin/ros  -Q  -L sbcl-bin dump executable ./roswell/silver-brain.ros" :OUTPUT :INTERACTIVE :ERROR-OUTPUT :INTERACTIVE)
    6: (ROSWELL:ROSWELL (" -Q " "-L" "sbcl-bin" "dump" "executable" "./roswell/silver-brain.ros") :INTERACTIVE NIL)
    7: (SB-INT:SIMPLE-EVAL-IN-LEXENV (APPLY (QUOTE MAIN) ROSWELL:*ARGV*) #<NULL-LEXENV>)
    8: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) #<NULL-LEXENV>)
    9: (SB-EXT:EVAL-TLF (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) NIL NIL)
    10: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) NIL)
    11: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS NIL {1003339393}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
    12: ((FLET SB-FASL::THUNK :IN LOAD))
    13: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<CLOSURE (FLET SB-FASL::THUNK :IN LOAD) {7FCE33B0753B}> #<CONCATENATED-STREAM :STREAMS NIL {1003339393}>)
    14: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<CONCATENATED-STREAM :STREAMS NIL {1003339393}> NIL)
    15: (LOAD #<CONCATENATED-STREAM :STREAMS NIL {1003339393}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
    16: ((FLET ROSWELL::BODY :IN ROSWELL:SCRIPT) #<SB-SYS:FD-STREAM for "file /etc/roswell/build.ros" {100332FDA3}>)
    17: (ROSWELL:SCRIPT "/etc/roswell/build.ros" "./roswell/silver-brain.ros")
    18: (ROSWELL:RUN ((:SCRIPT "/etc/roswell/build.ros" "./roswell/silver-brain.ros") (:QUIT NIL)))
    19: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:RUN (QUOTE ((:SCRIPT "/etc/roswell/build.ros" "./roswell/silver-brain.ros") (:QUIT NIL)))) #<NULL-LEXENV>)
    20: (EVAL (ROSWELL:RUN (QUOTE ((:SCRIPT "/etc/roswell/build.ros" "./roswell/silver-brain.ros") (:QUIT NIL)))))
    21: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(progn #-ros.init(cl:load \"/etc/roswell/init.lisp\"))") (:EVAL . "(ros:run '((:script \"/etc/roswell/build
    .ros\"\"./roswell/silver-brain.ros\")(:quit ())))")))
    22: (SB-IMPL::TOPLEVEL-INIT)
    23: ((FLET SB-UNIX::BODY :IN SB-EXT:SAVE-LISP-AND-DIE))
    24: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SB-EXT:SAVE-LISP-AND-DIE))
    25: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))

    unhandled condition in --disable-debugger mode, quitting
    Panic: Cannot build system

**Comment by sheepduke** [comment]
请注意下面这行日志：

```
 System "silver-brain" not found
```

你需要把 `silver-brain` 文件夹置于 ASDF 可以读取的地方，如 README 中所述：

> Before running it, you need to put Silver Brain project under a directory that your local ASDF can find, i.e. (ql:quickload :silver-brain) does work.

例如，在 `~/.roswell/local-projects/` 文件夹中创建一个指向 `silver-brain` 文件夹的符号链接。

我会把其加入 README。

另：建议贴日志的时候用引用或代码段格式。

**Comment by sheepduke** [comment]
Closed due to long-time inactivity.
